### PR TITLE
Pass the actual iterable from the option to get files

### LINKED ISSUE #137: Parsing error with comma-separated `--files` parameters
Seen during testing an internal application:

```
 Exception in thread "main" org.apache.spark.SparkException: File file:/path/to/logback.xml,file:/path/to/truststore.jks does not exist or is a directory.
     at org.apache.spark.deploy.kubernetes.Client$$anonfun$run$2.apply(Client.scala:84)
     at org.apache.spark.deploy.kubernetes.Client$$anonfun$run$2.apply(Client.scala:82)
     at scala.collection.immutable.List.foreach(List.scala:381)
     at org.apache.spark.deploy.kubernetes.Client.run(Client.scala:82)
     at org.apache.spark.deploy.kubernetes.Client$.main(Client.scala:810)
     at org.apache.spark.deploy.kubernetes.Client.main(Client.scala)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:747)
     at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:178)
     at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:203)
     at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:117)
     at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

cc @mccheah

### PR DESCRIPTION
**Pull request by mccheah**
Closes #137

### CODE REVIEW

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala [hunk 1]
```diff
@@ -77,8 +77,12 @@ private[spark] class Client(
 
   def run(): Unit = {
     logInfo(s"Starting application $kubernetesAppId in Kubernetes...")
-    val submitterLocalFiles = KubernetesFileUtils.getOnlySubmitterLocalFiles(sparkFiles)
-    val submitterLocalJars = KubernetesFileUtils.getOnlySubmitterLocalFiles(sparkJars)
+    val submitterLocalFiles = KubernetesFileUtils.getOnlySubmitterLocalFiles(sparkFiles
```
Comment (mccheah) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala]: We'll probably try to catch this at the unit test level, not the integration test level.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala [hunk 2]
```diff
@@ -77,8 +77,12 @@ private[spark] class Client(
...
+      .map(_.split(","))
+      .getOrElse(Array.empty[String]))
+    val submitterLocalJars = KubernetesFileUtils.getOnlySubmitterLocalFiles(sparkJars
```
Comment (ash211) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala]: the `sparkJars` and `sparkFiles` instance variables here are still in the comma-separated format which is a little unexpected.  They also don't have type annotations which maybe could've helped in review.

Maybe we should do the comma-splitting in the first access of `spark.files` and `spark.jars` and then annotate the types as `Iterable[String]` instead of the current implicit `Option[String]` ?

```
   private val sparkFiles = sparkConf.getOption("spark.files")
   private val sparkJars = sparkConf.getOption("spark.jars")
```

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala (hunk 1 above)
Comment (ash211) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala]: I'm not sure how you'll catch this at the unit test level -- won't you have to call the run() method to hit this, and won't that pretty much only be done in an integration test?

Comment (mccheah) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala]: I think we do want to call `run()` in the unit test however. Might take a decent amount of effort to mock everything, but it's probably the way to go.

**Comment by ash211** [comment]
Merging now, but I'm uncomfortable that we don't have a test that covers this so filed an issue at https://github.com/apache-spark-on-k8s/spark/issues/141
