### PR TITLE
Fail submission if submitter-local files are provided without resourc…

### LINKED ISSUE #339: Fail submission if the resource staging server URI isn't present but local files are submitted
Currently we don't validate this which could lead to confusing behavior.

### PR DESCRIPTION
**Pull request by sahilprasad**
…e staging server URI

Helpful validation to inhibit users from submitting local dependencies without specifying a URI for the RSS. Closes #339. 

## How was this patch tested?

Ran provided test suite and manually tested with local and non-local application dependency submissions.

### CODE REVIEW

**Comment by mccheah** [comment]
This is not necessarily the case with https://github.com/apache-spark-on-k8s/spark/pull/437

**Comment by ash211** [comment]
Hi @sahilprasad , thanks for the contribution to this project!

Just earlier today we merged a PR that supports sending "small files" from the submitter to drivers/executors via k8s secrets, for a definition of small.  If the files aren't small enough and no RSS is specified, then it throws this exception: https://github.com/apache-spark-on-k8s/spark/pull/437/files#diff-5fd183129559d8c0a34135c347be647bR40

For jars there's no small jar vs large jar distinction, so any time there's a local jar there must be an RSS specified.

Were you looking at this primarily because of files or because of jars?

**Comment by sahilprasad** [comment]
@ash211 I didn't realize that PR was there! I'm more concerned with jars here.
@mccheah Not necessarily as in small files submitted without an RSS specification will be sent through secrets, but not jars?

**Comment by mccheah** [comment]
Yeah sorry, to clarify, this change is still valid for jars, but we need to be more careful with local files.

**Comment by sahilprasad** [comment]
@mccheah Got it. If I were to change this just to accommodate jars, is there anything else in the way of jar-to-RSS validation that would be good to have?

**Comment by mccheah** [comment]
jars probably don't need any special case. I think local files is actually already handled by the small files bootstrap given that we do a best effort to mount as a secret but when the files are too large we print an informative error message.

**Comment by sahilprasad** [comment]
Right, is this change applicable, if modified, to just jars then?

**Comment by mccheah** [comment]
I think so - should be able to write a unit and/or integration test that covers this.

**Comment by sahilprasad** [comment]
@mccheah I can't get this test to pass when I build locally: https://github.com/apache-spark-on-k8s/spark/blob/branch-2.2-kubernetes/resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/kubernetes/submit/submitsteps/initcontainer/InitContainerConfigurationStepsOrchestratorSuite.scala#L72

Since the `SPARK_JARS` seq declared at the top of this class includes a submitter-local dependency (`file:///app/jars/jar2.txt`), that test fails with the validation error I am introducing with this PR. Since my test essentially constructs the orchestrator in the same way, and catches the thrown `IllegalArgumentException`, would that justify deleting this test?

**Comment by mccheah** [comment]
This indicates to me that the validation is being added at the incorrect location, because the init container configuration steps orchestrator should always be being built with the arguments already having been validated. In other words, the orchestrator itself shouldn't be doing the validation, but some component above it.

**Comment by mccheah** [comment]
Either that or the test should be patched to make it such that the orchestrator is created with "compatible" arguments - that is, if we're giving the orchestrator local files, it should also be given a resource staging server URI.

**Comment by sahilprasad** [comment]
@mccheah Where would the validation take place if not `InitContainerConfigurationStepsOrchestrator`? `DriverConfigurationStepsOrchestrator`? The former class already has some validation around the RSS, so I figured I'd put my code there.

One way that I see to patch the test in question would be to include only the first element of `SPARK_JARS` (the jar prepended with `hdfs://`). This leads to a successful build. Do you suggest an alternative to this, or does my patch suffice?

**Comment by mccheah** [comment]
The orchestrator can do the validation, but we should then change the test such that the arguments provided to the orchestrator line up with what the expectations are. We should be testing that

- When you use local jars, you must provide a resource staging server URI
- When you do not use local jars, it is not strictly necessary either way to provide this URI.

**Comment by sahilprasad** [comment]
@mccheah can you review?

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/submit/submitsteps/initcontainer/InitContainerConfigurationStepsOrchestrator.scala [hunk 1]
```diff
@@ -62,6 +62,15 @@ private[spark] class InitContainerConfigurationStepsOrchestrator(
     submissionSparkConf.get(RESOURCE_STAGING_SERVER_INTERNAL_SSL_ENABLED)
       .orElse(submissionSparkConf.get(RESOURCE_STAGING_SERVER_SSL_ENABLED))
       .getOrElse(false)
+
+  OptionRequirements.requireSecondIfFirstIsDefined(
+    KubernetesFileUtils.getOnlySubmitterLocalFiles(sparkJars).nonEmpty match {
```
Comment (mccheah) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/submit/submitsteps/initcontainer/InitContainerConfigurationStepsOrchestrator.scala]: Don't match on true or false here - use the functional APIs like `map`, `filter`, `getOrElse`, etc.

File: resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/kubernetes/submit/submitsteps/initcontainer/InitContainerConfigurationStepsOrchestratorSuite.scala [hunk 2]
```diff
@@ -44,6 +44,77 @@ class InitContainerConfigurationStepsOrchestratorSuite extends SparkFunSuite {
...
   private val STAGING_SERVER_URI = "http://localhost:8000"
 
+  test ("error thrown if local jars provided without resource staging server") {
+    val sparkConf = new SparkConf(true)
+      .set(KUBERNETES_DRIVER_LABELS, s"$DEPRECATED_CUSTOM_LABEL_KEY=$DEPRECATED_CUSTOM_LABEL_VALUE")
+      .set(s"$KUBERNETES_DRIVER_LABEL_PREFIX$CUSTOM_LABEL_KEY", CUSTOM_LABEL_VALUE)
+
+    assert(sparkConf.get(RESOURCE_STAGING_SERVER_URI).isEmpty)
+
+    intercept[IllegalArgumentException] {
```
Comment (mccheah) [inline resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/kubernetes/submit/submitsteps/initcontainer/InitContainerConfigurationStepsOrchestratorSuite.scala]: Can we inspect the correctness of the error message as well? We wouldn't want an `IllegalArgumentException` to come from some other part of the constructor.

**Review by mccheah — CHANGES_REQUESTED** [review]

**Review by mccheah — APPROVED** [review]

**Comment by mccheah** [comment]
Ok to merge once the build passes.

**Comment by sahilprasad** [comment]
@mccheah should I squash my commits, or is that done automatically?

**Comment by foxish** [comment]
@mccheah this good to merge?

File: resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/kubernetes/submit/submitsteps/initcontainer/InitContainerConfigurationStepsOrchestratorSuite.scala [hunk 3]
```diff
@@ -77,7 +151,7 @@ class InitContainerConfigurationStepsOrchestratorSuite extends SparkFunSuite {
     val orchestrator = new InitContainerConfigurationStepsOrchestrator(
       NAMESPACE,
       APP_RESOURCE_PREFIX,
-      SPARK_JARS,
+      SPARK_JARS.take(1),
```
Comment (ash211) [inline resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/kubernetes/submit/submitsteps/initcontainer/InitContainerConfigurationStepsOrchestratorSuite.scala:154]: this is a bit brittle in case SPARK_JARS changes in the future -- we should create a new `SPARK_JARS_REMOTE` that has only `hdfs://` path

**Comment by ash211** [comment]
Good to merge though, and Matt +1'd several weeks ago
