### PR TITLE
Flag-guard expensive DNS lookup of cluster node full names, part of HDFS locality support

### LINKED ISSUE #405: heartbeat timeout causing all executors exit
I run a spark application with 100 executors(each has 40G and 4cores),after running 4 hours,all executors exit with 56 and report the following logs:

```
...
Exit as unable to send heartbeats to driver more than 60 times
...
```

and driver hangs for several hours with nothing to do.

the relevant logs of driver list below:
```
2017-07-10 21:11:40 WARN  Executor:87 - Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Error sending message [message = Heartbeat(31,[Lscala.Tuple2;@641834e8,BlockManagerId(31, x.x.x.x, 57787, None))]
2017-07-10 21:11:49 WARN  Executor:87 - Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Error sending message [message = Heartbeat(52,[Lscala.Tuple2;@2de28748,BlockManagerId(52, x.x.x.x, 20423, None))]
2017-07-10 21:11:42 WARN  Executor:87 - Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Error sending message [message = Heartbeat(20,[Lscala.Tuple2;@431947f,BlockManagerId(20, x.x.x.x, 28993, None))]
2017-07-10 21:11:44 WARN  Executor:87 - Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Error sending message [message = Heartbeat(99,[Lscala.Tuple2;@6f8e1be0,BlockManagerId(99, x.x.x.x, 47398, None))]
2017-07-10 21:11:46 WARN  Executor:87 - Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Error sending message [message = Heartbeat(87,[Lscala.Tuple2;@6ff2c572,BlockManagerId(87, x.x.x.x, 47063, None))]
```

Addition:
1. Task Resources(1 driver + 100 executors)
driver: 40G+4cores
single executor: 40G+4cores

2. There are no user-specified spark configurations for this spark task. All using default ones.

3. It does not look like the network problem as other tasks in the same cluster run normally.

### PR DESCRIPTION
**Pull request by kimoonkim**
@hustcat @duyanghao @foxish 

## What changes were proposed in this pull request?

Fixes #405 by flag-guarding potentially heavy DNS lookup RPCs.

## How was this patch tested?

Modified existing unit tests to cover both flag-on and off cases.

### CODE REVIEW

**Comment by erikerlandson** [comment]
@kimoonkim is there an informative failure that can be detected, so that DNS lookup happens automatically **if** using the short name fails?  Sort of like a fallback.  Or is that failure scenario not possible to identify automatically?

**Comment by kimoonkim** [comment]
@erikerlandson Good question. It's hard to automatically detect specifically if DNS lookup is needed.

But we can automatically detect if the HDFS namenode is configured and use that as indication if HDFS support is needed. And flag guard the entire HDFS support. Curious what others think about this approach.

**Comment by erikerlandson** [comment]
I think it's a good idea to be able to enable/disable HDFS in general, especially if it has non-trivial performance implications

**Comment by kimoonkim** [comment]
@erikerlandson It just occurred to me that we can do adaptive approach. If DNS returns hostnames that are same as the cluster node names for a few hosts, then it is very likely that cluster node names are full hostnames. Then we don't need to issue more DNS requests. Thoughts?

**Comment by kimoonkim** [comment]
Yes. Unlike Spark on YARN, HDFS is an optional component for Spark on K8s. I don't think we want to force everyone to pay the performance cost.

Should I incorporate the broader flag in this PR or can it be a separate PR?

**Comment by erikerlandson** [comment]
it seems fine to me to incorporate the flag here, that ought to be a modest amount of code

**Comment by kimoonkim** [comment]
@erikerlandson @hustcat said in the issue that they use remote HDFS. ([comment](https://github.com/apache-spark-on-k8s/spark/issues/405#issuecomment-319849538)) So it may not work to automatically disable HDFS locality support based on whether the HDFS namenode is configured or not. (I'll make this change anyway because it would benefit others who don't use HDFS)

I think we still want to disable the DNS lookup by default. The bottom line is that DNS lookup turned out too expensive to do inside this critical section of the code. We'll have to redesign this part while disabling it for now. Perhaps we can issue DNS lookups asynchronously and pick up the results at a later point when the results are available.

**Comment by erikerlandson** [comment]
@kimoonkim that sounds like a good way to proceed

**Comment by kimoonkim** [comment]
@erikerlandson I was thinking about checking whether the HDFS namenode is configured or not in the `SparkContext.hadoopConfiguration`. i.e. Check the config key `fs.defaultFS` appear as `hdfs://HOST:PORT`. For non-HDFS users, the value would become one for local file system such as `file:///`, or one for s3 `s3a:///`, etc.

But on further thought, it seems this approach is error-prone. As the name `defaultFS` indicates this is only for the default. Job users can override this by putting the namenode address in any file paths for the jobs' input/output data, e.g. `hdfs://HOST:PORT/DIR1/FILE1`. In such case, the auto-detection logic will disable HDFS support code when it is actually needed.

Sorry about misleading the discussion. I think disabling the DNS lookup code is the best fix we can do for now, while redesigning the approach in the background.

**Review by ash211 — APPROVED** [review]
This seems like the right move until we can find a way to infer the flag.

Thanks folks for debugging!

**Comment by kimoonkim** [comment]
rerun integration tests please

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/config.scala [hunk 1]
```diff
@@ -500,6 +500,7 @@ package object config extends Logging {
         " The driver can slow down and fail to respond to executor heartbeats in time." +
         " If enabling this flag, make sure your DNS server has enough capacity" +
         " for the workload.")
+      .internal()
```
Comment (erikerlandson) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/config.scala]: what is the purpose of the `internal()` ?

Comment (kimoonkim) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/config.scala]: This makes the flag non-public. From the [code comment](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/internal/config/ConfigEntry.scala#L38):

>   @param isPublic if this configuration is public to the user. If it's `false`, this
configuration is only used internally and we should not expose it to users.

I think we want to redesign the DNS lookup code path so that this flag is not needed in the future. So keeping the flag internal allow us to remove it later without worrying if there are some users depend on it.

**Comment by kimoonkim** [comment]
Hmm, the Jenkins integration test is unhappy. I think I am seeing the same error that #389 reported about resource staging server timeout.

**Comment by kimoonkim** [comment]
rerun integration tests please

**Comment by liyinan926** [comment]
rerun integration tests please

**Comment by erikerlandson** [comment]
integration testing is probably going to have trouble passing until we fix #389, which should be soon

**Comment by liyinan926** [comment]
All tests passed. Can someone merge this so to unblock #416? Thanks!
