### PR TITLE
Generate the application ID label irrespective of app name.

### LINKED ISSUE #330: Generate pod labels as UUIDs rather than from Spark app name
We saw exceptions of this form when running an app:

`
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://example.com/apiserver/api/v1/namespaces/mynamespace/pods. Message: Pod "REDACTED" is invalid: [metadata.name: Invalid value: "REDACTED": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)* (e.g. 'example.com'), metadata.labels: Invalid value: "REDACTED": must be no more than 63 characters]. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.name, message=Invalid value: "REDACTED": must match the rege...
`

The problem is that Spark applies a label for all pods in the Spark application, and generates that label based on the Spark app name.  Previously Spark had no restrictions on Spark app name, so many apps out there have names that don't match the k8s requirements for label.  Because this label is only used internally to Spark (and users can create their own identifying labels via `spark.kubernetes.driver.labels` and `spark.kubernetes.executor.labels`) Spark should generate a label that is always a valid label name, rather than a label derived from the Spark app name.

A UUID would suffice.

### PR DESCRIPTION
**Pull request by mccheah**
Closes #330.

Use the application name as prefixes for Kubernetes resource names, but the restrictions on labels enforced by Kubernetes makes it untenable to put the application name in any labels. Therefore use a generated UUID as the "application ID" which we use both for registering with the external shuffle service and also when locating executor pods for the application.

### CODE REVIEW

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/config.scala [hunk 1]
```diff
@@ -151,6 +151,13 @@ package object config extends Logging {
       .stringConf
       .createOptional
 
+  private[spark] val KUBERNETES_EXECUTOR_POD_NAME_PREFIX =
+    ConfigBuilder("spark.kubernetes.executor.podNamePrefix")
+      .doc("Prefix to use in front of the executor pod names.")
+      .internal()
+      .stringConf
+      .createWithDefault("spark")
```
Comment (ash211) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/config.scala:159]: will this default ever be used?  seems the value will be set before its ever accessed

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/submit/Client.scala [hunk 2]
```diff
@@ -120,6 +120,7 @@ private[spark] class Client(
         .withName(kubernetesDriverPodName)
         .addToLabels(allLabels.asJava)
         .addToAnnotations(parsedCustomAnnotations.asJava)
+        .addToAnnotations(SPARK_APP_NAME_ANNOTATION, appName)
```
Comment (ash211) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/submit/Client.scala:143]: annotations don't have the same restrictions labels do?

**Review by ash211 — COMMENTED** [review]
We should add an integration test verifying that the restrictions on Spark app names have loosened.  After this do we expect application names of exactly 63 characters and containing non-DNS label characters like `_` to succeed?

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/submit/Client.scala (hunk 2 above)
Comment (mccheah) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/submit/Client.scala:143]: Doesn't seem that way since we put in full init-container specs in the annotations.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/config.scala (hunk 1 above)
Comment (mccheah) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/config.scala:159]: It's tricky because it's always set on the submission client, but in order to get the value directly we need to use `sparkConf.get(...)`. If the parameter is a config entry of type optional, then we need to call `.get` on the option, and require it to be present. I think it's ok if the contract is that it's always provided but there's still a default value here. At worst the executor names are incorrect but since we're doing all of our logic based on the ID label, it should not matter for correctness.

**Comment by mccheah** [comment]
@ash211 I added an integration test.

**Comment by mccheah** [comment]
I just tried a test and underscores aren't allowed in pod names either, unfortunately. Kubernetes documentation has the exact requirements - lowercase and numerical characters, dashes, and dots: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/config.scala (hunk 1 above)
Comment (erikerlandson) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/config.scala:159]: compromise with `...getOrElse("spark")`  ?

**Comment by erikerlandson** [comment]
if we rebase this on `branch-2.1-kubernetes` it should clear the out-of-date warning

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/config.scala (hunk 1 above)
Comment (mccheah) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/config.scala:159]: That would be more or less the same effect as this, so we might as well encode the default here - code in the config class is preferred over complexity in the scheduler backend class.

**Review by ash211 — APPROVED** [review]
LGTM -- this looks to significantly reduce exposure where the user provides a Spark app name that's reused for something in kubernetes and is then rejected.

Planning to merge when builds are green

**Comment by ash211** [comment]
rerun integration test please

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/constants.scala [hunk 3]
```diff
@@ -19,10 +19,12 @@ package org.apache.spark.deploy.kubernetes
...
   // Labels
   private[spark] val SPARK_DRIVER_LABEL = "spark-driver"
-  private[spark] val SPARK_APP_ID_LABEL = "spark-app-id"
-  private[spark] val SPARK_APP_NAME_LABEL = "spark-app-name"
+  private[spark] val SPARK_APP_ID_LABEL = "spark-app-selector"
   private[spark] val SPARK_EXECUTOR_ID_LABEL = "spark-exec-id"
   private[spark] val SPARK_ROLE_LABEL = "spark-role"
+  private[spark] val SPARK_POD_DRIVER_ROLE = "driver"
+  private[spark] val SPARK_POD_EXECUTOR_ROLE = "executor"
+  private[spark] val SPARK_APP_NAME_ANNOTATION = "spark-app-name"
```
Comment (erikerlandson) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/constants.scala:27]: Should "reserved" identifiers like "spark-app-name" in annotation keys be documented?

Comment (mccheah) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/constants.scala:27]: They could be but the error message might be self-documenting enough, and I'm not sure if it's worth the space. Do you anticipate this being an annotation that people will want to set?

Comment (erikerlandson) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/constants.scala:27]: It seems more like a low-prob corner case.  If it's a lot of doc, then might not be worth it.  If it's low effort then I'd consider it worth doing

Comment (erikerlandson) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/constants.scala:27]: Mostly would be worried if there is potential for silent failures

Comment (mccheah) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/constants.scala:27]: We send the notification here: https://github.com/apache-spark-on-k8s/spark/pull/331/files#diff-8c861c0709460ebb9571f0d44791b6beR92
