### PR TITLE
Check for user jars/files existence before creating the driver pod.

### LINKED ISSUE #85: Check the existence of the user jars/files before creating the driver pod/service
If the user jars/files doesn't exist (or there is a typo), it's better to fail before creating the driver pod/service.

### PR DESCRIPTION
**Pull request by lins05**
Closes #85

### CODE REVIEW

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala [hunk 1]
```diff
@@ -661,6 +665,33 @@ private[spark] class Client(
       }).toMap
     }).getOrElse(Map.empty[String, String])
   }
+
+  private def checkForUserJarsFilesExistence: Unit = {
```
Comment (mccheah) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala]: I think the trend has been for these kinds of precondition methods to pass the appropriate things to inspect as parameters, as opposed to inspecting the instance variables directly.  We also have been running the validation inside of `run()` as opposed to in the constructor. See `parseCustomLabels()` for example.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala [hunk 2]
```diff
@@ -661,6 +665,33 @@ private[spark] class Client(
...
+    val conf = new Configuration
+
+    def existsOrAbort(uri: URI): Unit = {
```
Comment (mccheah) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala]: I'd rather avoid nesting methods here. We can just inline this logic in the case statement of `checkExistence`.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala [hunk 3]
```diff
@@ -661,6 +665,33 @@ private[spark] class Client(
...
+      val path = new Path(uri)
+      if (!path.getFileSystem(conf).isFile(path)) {
```
Comment (mccheah) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala]: If we inline this in the `case` statement, it becomes clear that the scheme is of type `file`. Then instead of using `getFileSystem` we can just use an instance of `java.io.File` instance from the path component of the URI. This is the pattern we follow elsewhere, see `buildSubmissionRequest()`.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala [hunk 4]
```diff
@@ -661,6 +665,33 @@ private[spark] class Client(
...
+        throw new SparkException(s"""file "${uri}" does not exist!""")
+      }
+    }
+
+    def checkExistence(maybePaths: Option[String]): Unit = {
```
Comment (mccheah) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala]: Again, avoid nested methods. We can make this be the outermost method, and then `run()` can just call this three times, once for each of the appropriate fields to inspect.

**Review by mccheah — CHANGES_REQUESTED** [review]
Thanks for submitting this, it indeed does make sense to push as much precondition checking as early as possible. I've left some comments.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala [hunk 5]
```diff
@@ -64,6 +68,7 @@ private[spark] class Client(
   private val uploadedJars = sparkConf.get(KUBERNETES_DRIVER_UPLOAD_JARS).filter(_.nonEmpty)
   private val uploadedFiles = sparkConf.get(KUBERNETES_DRIVER_UPLOAD_FILES).filter(_.nonEmpty)
   uploadedFiles.foreach(validateNoDuplicateUploadFileNames)
+  checkForUserJarsFilesExistence
```
Comment (ash211) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala]: put parentheses around zero-param methods like `checkForUserJarsFilesExistence()` -- I think this is Spark style

**Review by ash211 — COMMENTED** [review]
I support failing fast!

**Comment by lins05** [comment]
@mccheah @ash211 updated.

**Review by mccheah — APPROVED** [review]

**Comment by mccheah** [comment]
@aash anything else to add? Otherwise feel free to merge when the build passes.

**Comment by ash211** [comment]
Thanks @lins05 !
