### PR TITLE
Use node affinity to launch executors on preferred nodes benefitting from data locality

### LINKED ISSUE #315: Use nodeAffinity to launch executors on cluster nodes that benefit from HDFS data locality
@foxish @ash211

This is a sub-issue of the HDFS data locality issue #206.

When using HDFS, the Spark driver sends tasks to particular executors that have tasks' HDFS data on local disks. (Implemented in #216)

To increase the chance of benefitting from data locality, the driver should also launch executors on cluster nodes that have tasks' HDFS data in the first place if possible.

There are a few Spark core base classes that update the key data structure `hostToLocalTaskCount`, which contains a map of cluster nodes to the number of tasks that could benefit from data locality if tasks run on the cluster node.

1. [ExecutorAllocationManager](https://github.com/apache-spark-on-k8s/spark/blob/branch-2.1-kubernetes/core/src/main/scala/org/apache/spark/ExecutorAllocationManager.scala) listens to a newly submitted stage and looks at the partition locations of the stage input data. The cluster nodes that have the partition locations will increase the task count.
```
   override def onStageSubmitted(stageSubmitted: SparkListenerStageSubmitted): Unit = {
       ...
        stageSubmitted.stageInfo.taskLocalityPreferences.foreach { locality =>
          if (!locality.isEmpty) {
            numTasksPending += 1
            locality.foreach { location =>
              val count = hostToLocalTaskCountPerStage.getOrElse(location.host, 0) + 1
              hostToLocalTaskCountPerStage(location.host) = count
            }
          }
        }
        stageIdToExecutorPlacementHints.put(stageId,
          (numTasksPending, hostToLocalTaskCountPerStage.toMap))

        // Update the executor placement hints
        updateExecutorPlacementHints()
      }
    }

  def updateExecutorPlacementHints(): Unit = {
      var localityAwareTasks = 0
      val localityToCount = new mutable.HashMap[String, Int]()
      stageIdToExecutorPlacementHints.values.foreach { case (numTasksPending, localities) =>
        localityAwareTasks += numTasksPending
        localities.foreach { case (hostname, count) =>
          val updatedCount = localityToCount.getOrElse(hostname, 0) + count
          localityToCount(hostname) = updatedCount
        }
      }

      allocationManager.localityAwareTasks = localityAwareTasks
      allocationManager.hostToLocalTaskCount = localityToCount.toMap
    }
```
2. [CoarseGrainedSchedulerBackend](https://github.com/apache-spark-on-k8s/spark/blob/branch-2.1-kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/CoarseGrainedSchedulerBackend.scala) will be informed of `hostToLocalTaskCount` and stores a snapshot.
```
  final override def requestTotalExecutors(
      numExecutors: Int,
      localityAwareTasks: Int,
      hostToLocalTaskCount: Map[String, Int]
    ): Boolean = {
    if (numExecutors < 0) {
      throw new IllegalArgumentException(
        "Attempted to request a negative number of executor(s) " +
          s"$numExecutors from the cluster manager. Please specify a positive number!")
    }

    val response = synchronized {
      this.localityAwareTasks = localityAwareTasks
      this.hostToLocalTaskCount = hostToLocalTaskCount

      numPendingExecutors =
        math.max(numExecutors - numExistingExecutors + executorsPendingToRemove.size, 0)

      doRequestTotalExecutors(numExecutors)
    }

    defaultAskTimeout.awaitResult(response)
  }
```

In K8s, we can use K8s `nodeAffinity` ([doc](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature)) 
 in `KubernetesClusterSchedulerBackend`, which is a subclass of CoarseGrainedSchedulerBackend, to express this preference. In particular, `preferredDuringSchedulingIgnoredDuringExecution` can express soft requirement. From the doc:
> There are currently two types of node affinity, called requiredDuringSchedulingIgnoredDuringExecution and preferredDuringSchedulingIgnoredDuringExecution. You can think of them as “hard” and “soft” respectively, in the sense that the former specifies rules that must be met for a pod to schedule onto a node (just like nodeSelector but using a more expressive syntax), while the latter specifies preferences that the scheduler will try to enforce but will not guarantee. The “IgnoredDuringExecution” part of the names means that, similar to how nodeSelector works, if labels on a node change at runtime such that the affinity rules on a pod are no longer met, the pod will still continue to run on the node.

I'll send a PR soon to address this need.

### PR DESCRIPTION
**Pull request by kimoonkim**
@foxish @ash211 

Closes #315 

Manually tested with org.apache.spark.examples.HdfsTest while enabling dynamic allocation:
>  $ /usr/local/spark-on-k8s/bin/spark-submit --class org.apache.spark.examples.HdfsTest --conf spark.app.name=spark-hdfstest --conf spark.dynamicAllocation.enabled=true --conf spark.shuffle.service.enabled=true --conf spark.kubernetes.shuffle.labels="app=spark-shuffle-service,spark-version=2.1.0" /usr/local/spark-on-k8s/examples/jars/spark-examples_2.11-2.1.0-k8s-0.1.0-SNAPSHOT.jar terasort-in-150G

From the driver log:
```
2017-05-30 18:31:07 INFO  KubernetesClusterSchedulerBackend:54 - Adding nodeAffinity as annotation {
          "nodeAffinity": {
            "preferredDuringSchedulingIgnoredDuringExecution": [
            {
                    "weight": 36,
                    "preference": {
                      "matchExpressions": [{
                        "key": "kubernetes.io/hostname",
                        "operator": "In",
                        "values": ["kube-n1.pepperdata.com"]
                      }]
                    }
                  }
               ,{
                    "weight": 63,
                    "preference": {
                      "matchExpressions": [{
                        "key": "kubernetes.io/hostname",
                        "operator": "In",
                        "values": ["kube-n4.pepperdata.com"]
                      }]
                    }
                  }

            ]
          }
        }
```

From `$ kubectl get pod` of the executor pod:
> "scheduler.alpha.kubernetes.io/affinity": "{\"nodeAffinity\": {\"preferredDuringSchedulingIgnoredDuringExecution\":[{\"weight\":17,\"preference\":{\"matchExpressions\":[{\"key\":\"kubernetes.io/hostname\",\"operator\":\"In\",\"values\":[\"kube-n7.pepperdata.com\"]}]}},{\"weight\":18,\"preference\":{\"matchExpressions\":[{\"key\":\"kubernetes.io/hostname\",\"operator\":\"In\",\"values\":[\"kube-n9.pepperdata.com\",\"kube-n4.pepperdata.com\"]}]}},{\"weight\":16,\"preference\":{\"matchExpressions\":[{\"key\":\"kubernetes.io/hostname\",\"operator\":\"In\",\"values\":[\"kube-n10.pepperdata.com\"]}]}},{\"weight\":11,\"preference\":{\"matchExpressions\":[{\"key\":\"kubernetes.io/hostname\",\"operator\":\"In\",\"values\":[\"kube-n1.pepperdata.com\"]}]}},{\"weight\":19,\"preference\":{\"matchExpressions\":[{\"key\":\"kubernetes.io/hostname\",\"operator\":\"In\",\"values\":[\"kube-n5.pepperdata.com\"]}]}}]}}"

### CODE REVIEW

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala [hunk 1]
```diff
@@ -17,16 +17,18 @@
 package org.apache.spark.scheduler.cluster.kubernetes
 
 import java.io.Closeable
+import java.net.InetAddress
 import java.util.concurrent.TimeUnit
 import java.util.concurrent.atomic.{AtomicInteger, AtomicLong, AtomicReference}
 
+import scala.collection.JavaConverters._
```
Comment (mccheah) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: Think these imports should not have moved.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala [hunk 2]
```diff
@@ -154,10 +156,24 @@ private[spark] class KubernetesClusterSchedulerBackend(
...
       } else {
+        val executorPodsWithIPs = EXECUTOR_PODS_BY_IPS_LOCK.synchronized {
+            executorPodsByIPs.values.toList
+          }
+        val nodeToLocalTaskCount = mutable.Map[String, Int]() ++
+          KubernetesClusterSchedulerBackend.this.synchronized {
+            hostToLocalTaskCount
+          }
+        for (pod <- executorPodsWithIPs) {
+          nodeToLocalTaskCount.remove(pod.getSpec.getNodeName).nonEmpty ||
```
Comment (mccheah) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: What's exactly the net result of this block?

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala [hunk 3]
```diff
@@ -348,14 +370,49 @@ private[spark] class KubernetesClusterSchedulerBackend(
...
+    val resolvedExecutorPodBuilder = if (nodeToTaskCount.nonEmpty) {
+      val taskTotal = nodeToTaskCount.foldLeft(0)(_ + _._2)
+      // Normalize to node affinity weights in 1 to 100 range.
+      val nodeToWeight = nodeToTaskCount.map{
+        case (node, taskCount) =>
+          (node, math.min(100, math.max(1, math.round(taskCount * 100.0 / taskTotal))))}
+      val weightToNodes = nodeToWeight.values.map(
+        weight => (weight, nodeToWeight.keys.filter(nodeToWeight(_) == weight))).toMap
+      // TODO: Use non-annotation syntax when we switch to K8s version 1.6.
+      val nodeAffinity = s"""{
```
Comment (mccheah) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: Is `NodeAffinity` a construct that isn't supported by the Fabric8 client? It might be better to add an object model there that has a serializer to and from YAML/JSON that we can then add here.

To unblock us for now we can build the POJO class in this project with the appropriate Jackson annotations that allow it to be serialized and deserialized with an `ObjectMapper`.

**Review by mccheah — CHANGES_REQUESTED** [review]

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala (hunk 2 above)
Comment (kimoonkim) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: This removes cluster nodes that are running our executor pods already since we don't need to launch more executors on those nodes. I'll add a comment.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala (hunk 3 above)
Comment (kimoonkim) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: Not in the current version of Fabric8 client. `NodeAffinity` became a beta feature in K8s 1.6. So I assume a new version of Fabric8 client with 1.6 support will have a construct for `NodeAffinity`.

The POJO json object idea sounds good to me. I'll try that in the next commit.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala (hunk 1 above)
Comment (kimoonkim) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: Fixed.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala (hunk 2 above)
Comment (kimoonkim) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: Added a comment.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala (hunk 3 above)
Comment (kimoonkim) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: Fixed. Used case classes with `ObjectMapper`.

**Comment by kimoonkim** [comment]
@mccheah Thanks for the comments. Addressed them in a new diff. PTAL.

**Comment by kimoonkim** [comment]
Tested again with the new patch. It seems the json from the object mapper works.

**Comment by ash211** [comment]
@kimoonkim looks like there's a merge conflict here still

**Comment by kimoonkim** [comment]
@ash211 Resolved the conflict. Thanks.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala [hunk 4]
```diff
@@ -279,7 +299,13 @@ private[spark] class KubernetesClusterSchedulerBackend(
...
   }
 
-  private def allocateNewExecutorPod(): (String, Pod) = {
+  /**
+   * Allocates a new executor pod
+   * @param nodeToTaskCount A map of K8s cluster nodes to the number of tasks that could benefit
+   *                        from data locality if an executor launches on the cluster node.
+   * @return A tuple of the new executor name and the Pod data structure.
+   */
+  private def allocateNewExecutorPod(nodeToTaskCount: Map[String, Int]): (String, Pod) = {
```
Comment (ash211) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: this method has grown to >150 lines -- maybe a followup PR can shrink it by refactoring in some way?

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala [hunk 5]
```diff
@@ -389,14 +415,40 @@ private[spark] class KubernetesClusterSchedulerBackend(
...
-        withMaybeShuffleConfigPodBuilder)
-    }.getOrElse(withMaybeShuffleConfigPodBuilder)
+    val executorInitContainerPodBuilder = executorInitContainerBootstrap.map {
+        bootstrap =>
+          bootstrap.bootstrapInitContainerAndVolumes(
+            "executor",
+            withMaybeShuffleConfigPodBuilder)
+      }.getOrElse(withMaybeShuffleConfigPodBuilder)
+
+    val resolvedExecutorPodBuilder = if (nodeToTaskCount.nonEmpty) {
```
Comment (ash211) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: can you pull this out into an `addNodeAffinityAnnotationIfUseful` method?

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala [hunk 6]
```diff
@@ -517,3 +569,9 @@ private object KubernetesClusterSchedulerBackend {
   private val DEFAULT_STATIC_PORT = 10000
   private val EXECUTOR_ID_COUNTER = new AtomicLong(0L)
 }
+
+case class NodeAffinity(preferredDuringSchedulingIgnoredDuringExecution:
+                        Iterable[WeightedPreference])
+case class WeightedPreference(weight: Int, preference: Preference)
+case class Preference(matchExpressions: Array[MatchExpression])
+case class MatchExpression(key: String, operator: String, values: Iterable[String])
```
Comment (ash211) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala:610]: is there a k8s spec that these are following?  if so please add a comment above these case classes with a link to k8s docs on what they mean

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala [hunk 7]
```diff
@@ -389,14 +415,40 @@ private[spark] class KubernetesClusterSchedulerBackend(
...
+            "executor",
+            withMaybeShuffleConfigPodBuilder)
+      }.getOrElse(withMaybeShuffleConfigPodBuilder)
+
+    val resolvedExecutorPodBuilder = if (nodeToTaskCount.nonEmpty) {
+      val taskTotal = nodeToTaskCount.foldLeft(0)(_ + _._2)
+      // Normalize to node affinity weights in 1 to 100 range.
+      val nodeToWeight = nodeToTaskCount.map{
+        case (node, taskCount) =>
+          (node, math.min(100, math.max(1, math.round(taskCount * 100.0 / taskTotal).toInt)))}
```
Comment (ash211) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: method here named `scaleToRange` ?

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala [hunk 8]
```diff
@@ -389,14 +415,40 @@ private[spark] class KubernetesClusterSchedulerBackend(
...
+      val weightToNodes = nodeToWeight.values.map(
+        weight => (weight, nodeToWeight.keys.filter(nodeToWeight(_) == weight))).toMap
```
Comment (ash211) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: does scala have a map invert method we could use here?

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala [hunk 9]
```diff
@@ -389,14 +415,40 @@ private[spark] class KubernetesClusterSchedulerBackend(
...
+      val nodeAffinity = NodeAffinity(preferredDuringSchedulingIgnoredDuringExecution =
+          for ((weight, nodes) <- weightToNodes) yield
+            WeightedPreference(weight,
+              Preference(Array(MatchExpression("kubernetes.io/hostname", "In", nodes))))
+        )
+      val nodeAffinityJson =
+        s"""{"nodeAffinity": ${objectMapper.writeValueAsString(nodeAffinity)}}"""
+
+      // TODO: Use non-annotation syntax when we switch to K8s version 1.6.
```
Comment (ash211) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: link to what this syntax looks like?

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala [hunk 10]
```diff
@@ -182,10 +185,25 @@ private[spark] class KubernetesClusterSchedulerBackend(
       } else if (totalExpectedExecutors.get() <= runningExecutorPods.size) {
         logDebug("Maximum allowed executor limit reached. Not scaling up further.")
       } else {
+        val executorPodsWithIPs = EXECUTOR_PODS_BY_IPS_LOCK.synchronized {
+            executorPodsByIPs.values.toList
```
Comment (ash211) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: does this make a defensive copy of the values?  I think we want a defensive copy here

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala [hunk 11]
```diff
@@ -182,10 +185,25 @@ private[spark] class KubernetesClusterSchedulerBackend(
...
+            hostToLocalTaskCount
+          }
+        for (pod <- executorPodsWithIPs) {
+          // Remove cluster nodes that are running our executors already.
+          nodeToLocalTaskCount.remove(pod.getSpec.getNodeName).nonEmpty ||
+            nodeToLocalTaskCount.remove(pod.getStatus.getHostIP).nonEmpty ||
+            nodeToLocalTaskCount.remove(
+              InetAddress.getByName(pod.getStatus.getHostIP).getCanonicalHostName).nonEmpty
+        }
+        val preferredNodes = nodeToLocalTaskCount.toMap[String, Int]
```
Comment (ash211) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: can you pull this chunk of code out into a method named something like `currentNodesWithTaskCounts`

Also don't like the name `preferredNodes` here -- this doesn't contain the preferred nodes for the new executor, it's actually a list of nodes that don't currently have executors along with their task count. 
 Which is later converted into a prioritization

**Review by ash211 — COMMENTED** [review]
Looks great @kimoonkim !  I think this is a hot code path for jobs that scale up quickly, so want to make sure it's well-optimized and won't slow down launching new nodes.  I don't see any extraneous network calls or lots of computation being done here, it looks like mostly map manipulation which hopefully isn't terrible.  Do you see any ways to make this addition even more efficient than it already is?

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala (hunk 10 above)
Comment (kimoonkim) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: Yes, it does. The output is an immutable list while the map is a mutable hashmap, so the toList copies the values to make an immutable list. I'll add a comment.

```
scala> val a = scala.collection.mutable.HashMap("a" -> 1, "b" -> 2)
a: scala.collection.mutable.HashMap[String,Int] = Map(b -> 2, a -> 1)

scala> val b = a.values.toList
b: List[Int] = List(2, 1)

scala> a -= "b"
res1: a.type = Map(a -> 1)

scala> a.values
res2: Iterable[Int] = HashMap(1)

scala> b
res3: List[Int] = List(2, 1)

scala> a -= "a"
res4: a.type = Map()

scala> a.values
res5: Iterable[Int] = HashMap()

scala> b
res6: List[Int] = List(2, 1)
```

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala (hunk 11 above)
Comment (kimoonkim) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: Fixed.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala (hunk 4 above)
Comment (kimoonkim) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: I think we can factor out each builder into a separate method like what we did with `addNodeAffinityAnnotationIfUseful` below.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala (hunk 5 above)
Comment (kimoonkim) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: Fixed.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala (hunk 7 above)
Comment (kimoonkim) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: Fixed.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala (hunk 8 above)
Comment (kimoonkim) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: I couldn't find invert, but used a shorter version of this trick.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala (hunk 9 above)
Comment (kimoonkim) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: Fixed.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala (hunk 6 above)
Comment (kimoonkim) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala:610]: Fixed.

**Comment by kimoonkim** [comment]
Thanks for the great comments @ash211. Addressed them. PTAL.

**Comment by ash211** [comment]
@kimoonkim looks like there's a scalastyle issue: http://spark-k8s-jenkins.pepperdata.org:8080/job/PR-spark-k8s-full-build/525/consoleFull#-1961731639853a0453-9a85-4740-a867-694552c49a93

**Comment by kimoonkim** [comment]
rerun unit tests please

**Comment by ash211** [comment]
Going to return to this after the log4j change

**Comment by ash211** [comment]
That's in, will babysit jenkins for this PR now..

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala [hunk 12]
```diff
@@ -283,7 +290,63 @@ private[spark] class KubernetesClusterSchedulerBackend(
...
+  private def getCurrentNodesWithTaskCounts() : Map[String, Int] = {
+    val executorPodsWithIPs = EXECUTOR_PODS_BY_IPS_LOCK.synchronized {
+      executorPodsByIPs.values.toList  // toList makes a defensive copy.
+    }
+    val nodeToLocalTaskCount = mutable.Map[String, Int]() ++
+      KubernetesClusterSchedulerBackend.this.synchronized {
+        hostToLocalTaskCount
+      }
+    for (pod <- executorPodsWithIPs) {
+      // Remove cluster nodes that are running our executors already.
```
Comment (ash211) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala:306]: Is preferring not-previously-used executors always a good idea?  It reminds me of the `spark.deploy.spreadOut` flag that Spark standalone has: https://spark.apache.org/docs/latest/spark-standalone.html

If you were doing a highly iterative workload that was network bound, it may be better to allow (or even prefer!) scheduling multiple executor pods on the same k8s node so that network is only on the loopback interface rather than actually crossing between servers.

Possibly we should consider adding a flag for this in the future.  The typical job I would run would prefer the spread out mode you have here so I'm not in a rush to support the consolidated mode.

**Comment by ash211** [comment]
@mccheah you still have requested changes on this PR -- have those been resolved?

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala (hunk 12 above)
Comment (kimoonkim) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala:306]: That is a great question. Good to learn about the `spark.deploy.spreadOut` flag. I agree we should consider a flag for this in the future. I'll add a TODO here.

One interesting related fact is that the loop at line 192 - 197 may have the effect of consolidated mode within the next batch of pods, because we are not changing nodes within this loop. But we don't know how much consolidation will be done by the scheduler.
```
           for (i <- 0 until math.min(
             totalExpectedExecutors.get - runningExecutorPods.size, podAllocationSize)) {
            runningExecutorPods += allocateNewExecutorPod(nodeToTaskCount)
             logInfo(
               s"Requesting a new executor, total executors is now ${runningExecutorPods.size}")
           }

**Review by ash211 — APPROVED** [review]
LGTM - @mccheah ?

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala [hunk 13]
```diff
@@ -283,7 +290,71 @@ private[spark] class KubernetesClusterSchedulerBackend(
...
+          (node, scaleToRange(taskCount, 1, taskTotal, rangeMin = 1, rangeMax = 100))}
+      val weightToNodes = nodeToWeight.groupBy(_._2).mapValues(_.keys)
+      // @see https://kubernetes.io/docs/concepts/configuration/assign-pod-node
+      val nodeAffinity = NodeAffinity(preferredDuringSchedulingIgnoredDuringExecution =
+        for ((weight, nodes) <- weightToNodes) yield
+          WeightedPreference(weight,
+            Preference(Array(MatchExpression("kubernetes.io/hostname", "In", nodes))))
+      )
+      val nodeAffinityJson =
+        s"""{"nodeAffinity": ${objectMapper.writeValueAsString(nodeAffinity)}}"""
```
Comment (mccheah) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: Can this be written directly? the `nodeAffinity` portion.

Comment (mccheah) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: As in I don't think we should have to write any strings manually here, the ObjectMapper should create the entire structure for us.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala [hunk 14]
```diff
@@ -521,3 +597,12 @@ private object KubernetesClusterSchedulerBackend {
   private val DEFAULT_STATIC_PORT = 10000
   private val EXECUTOR_ID_COUNTER = new AtomicLong(0L)
 }
+
+// These case classes model K8s node affinity syntax for
```
Comment (mccheah) [inline resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: Use `/** ... */` style comments for something like this, particularly if we're embedding an `@see` tag below.

**Review by mccheah — APPROVED** [review]
Looks fine - address the small comments and then feel free to merge immediately afterwards.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala (hunk 13 above)
Comment (kimoonkim) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: Done and done.

File: resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala (hunk 14 above)
Comment (kimoonkim) [reply resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala]: Done. Good point.

**Comment by kimoonkim** [comment]
Thanks @ash211 @mccheah for reviews!

**Comment by erikerlandson** [comment]
rerun unit tests please

**Comment by ash211** [comment]
Thanks for the contribution @kimoonkim !  Glad to have this in here now
